/**
 * Bethany Network Manager — Core Data Models
 *
 * These interfaces define the shape of data throughout the system.
 * They map directly to D1 tables (schema.sql) and are used by every
 * service layer module.
 *
 * Conventions:
 *   - DB row types use snake_case (matching D1 column names)
 *   - Application-level types use camelCase
 *   - "Row" suffix = raw D1 result shape
 *   - No "Row" suffix = application-level shape (services transform as needed)
 *   - All IDs are UUIDs stored as TEXT in D1
 *   - All dates are ISO 8601 strings (D1 stores TEXT)
 */

// ===========================================================================
// Enums & Literal Types
// ===========================================================================

/**
 * Relationship intent — how the user intends to maintain this contact.
 * Drives cadence defaults and health calculations.
 * Detailed config (cadence days, descriptions, nudge templates) lives
 * in shared/intent-config.ts (TASK-f94df59b-a).
 */
export type IntentType =
  | 'inner_circle'   // Closest relationships — frequent, deep contact
  | 'nurture'        // Growing relationships — regular investment
  | 'maintain'       // Stable relationships — periodic check-ins
  | 'transactional'  // Purpose-driven — as needed
  | 'dormant'        // Paused — no active cadence
  | 'new';           // Just added — needs sorting

/**
 * Contact health status — derived from intent cadence vs. last contact date.
 * Calculated by calculateHealthStatus() in intent-config.ts.
 */
export type HealthStatus = 'green' | 'yellow' | 'red';

/**
 * Contact kind — whether this contact is family (kin) or not.
 * Kin contacts receive relaxed cadence thresholds because research shows
 * family relationships resist decay even with reduced contact frequency.
 *
 * @see Roberts & Dunbar (2011). The costs of family and friends.
 * @see Roberts & Dunbar (2015). Managing relationship decay.
 */
export type ContactKind = 'kin' | 'non_kin';

/**
 * User gender — optional, set during onboarding or in settings.
 *
 * Used to apply soft defaults for nudge cadence and style preferences.
 * This is NOT prescriptive — it informs Bethany's suggestions, which
 * the user can always override. Think of it like the kin/non-kin
 * distinction: a research-backed default that improves the experience
 * for most people without being a hard rule.
 *
 * Research basis (Roberts & Dunbar 2011, 2015):
 *   - Women maintain relationships primarily through conversation
 *     frequency — more frequent check-ins, conversation-based nudges.
 *   - Men maintain relationships primarily through shared activities —
 *     activity-based prompts, doing-things-together suggestions.
 *   - Women tend to have slightly larger sympathy groups (Layer 2)
 *     with more emotional depth per connection.
 *   - Men tend to have larger but less intimate outer layers.
 *
 * null = not set (no gender modifiers applied).
 *
 * @see GenderModifiers in shared/intent-config.ts
 * @see dunbar-cadence-research-findings.md, Section 4 (Relationship Decay Research)
 */
export type UserGender = 'male' | 'female' | null;

/**
 * Drift severity — how far a contact's actual interaction frequency
 * has diverged from their assigned Dunbar layer.
 *
 * This is distinct from HealthStatus. Health measures against ONE cadence
 * (the contact's assigned intent). Drift compares against ALL layer
 * thresholds to detect layer migration.
 *
 * - watching:  frequency is trending toward the next lower layer
 *              but hasn't crossed the boundary yet. Early warning.
 * - drifting:  frequency has crossed into the cadence range of a
 *              lower layer. Active migration in progress.
 * - fallen:    frequency matches a layer 2+ below their assigned one.
 *              The relationship has effectively migrated.
 *
 * @see detectDrift() in intent-config.ts
 */
export type DriftSeverity = 'watching' | 'drifting' | 'fallen';

/**
 * Drift alert — signals that a contact's actual interaction pattern
 * doesn't match their assigned Dunbar layer.
 *
 * Generated by detectDrift() in intent-config.ts. These are not persisted
 * in D1 — they're computed on-demand (during cron or dashboard load)
 * from the interactions table.
 *
 * Example: A contact assigned to inner_circle (7-day cadence) who
 * averages 35 days between interactions over the last 90 days is
 * behaving like a maintain-layer contact. The drift alert would show:
 *   currentLayer: 'inner_circle'
 *   driftingTowardLayer: 'maintain'
 *   severity: 'fallen' (skipped past nurture entirely)
 *
 * This is the core differentiator from every competitor (Clay, Dex,
 * UpHabit) — none implement cross-layer frequency comparison.
 */
export interface DriftAlert {
  /** The contact this alert is for */
  contactId: string;
  /** The contact's assigned intent/layer */
  currentLayer: IntentType;
  /** The layer their actual frequency matches */
  driftingTowardLayer: IntentType;
  /** How severe the drift is */
  severity: DriftSeverity;
  /** Evidence for the drift detection */
  evidence: DriftEvidence;
  /** When this drift was detected */
  detectedAt: string;
}

/**
 * Evidence supporting a drift detection — the numbers behind the alert.
 * Gives both Bethany and the dashboard enough data to explain the drift.
 */
export interface DriftEvidence {
  /** Average days between interactions in the assessment window */
  avgInteractionInterval: number;
  /** Expected cadence for the contact's assigned layer */
  expectedCadenceDays: number;
  /** Cadence of the layer they're drifting toward */
  matchedLayerCadenceDays: number;
  /** Number of interactions in the assessment window */
  interactionCount: number;
  /** How many days the assessment window covers */
  windowDays: number;
  /** Days since last interaction (for context) */
  daysSinceLastContact: number;
}

/**
 * Subscription tier — determines feature access and limits.
 */
export type SubscriptionTier = 'free' | 'trial' | 'premium';

/**
 * Interaction method — how the user connected with a contact.
 */
export type InteractionMethod =
  | 'text'       // SMS/iMessage
  | 'call'       // Phone call
  | 'in_person'  // Face-to-face
  | 'email'      // Email
  | 'social'     // Social media
  | 'other';

/**
 * Circle type — categorization for grouping contacts.
 */
export type CircleType =
  | 'default'    // System-provided (e.g., Family, Friends, Work)
  | 'custom';    // User-created

/**
 * Onboarding conversation stages — post-signup SMS flow state machine.
 *
 * Updated for web-first flow (TASK-36776bae-4). The old SMS-first stages
 * (greeting, learn_name, send_signup_link) are removed. Signup now
 * happens on the web form first, then Bethany texts to start onboarding.
 *
 * Flow: web signup → Bethany sends intro → user replies → conversation
 *
 * @see worker/services/onboarding-service.ts for the full state machine
 */
export type OnboardingStage =
  | 'intro_sent'        // Bethany's welcome message delivered after web signup
  | 'user_replies'      // User responded, getting to know them
  | 'learn_circles'     // Identifying key relationships and groups
  | 'explain_features'  // Showing what Bethany can do
  | 'ready';            // Onboarding complete, user is active

/**
 * Trial reminder stages — lifecycle messaging touchpoints.
 *
 * Tracks which trial-related messages have been sent to avoid duplicates.
 * Stages progress in order: signup → usage_highlight → upgrade_prompt → expired.
 *
 * @see worker/services/trial-messaging-service.ts
 */
export type TrialReminderStage =
  | 'signup'          // Initial "14 days full access" message
  | 'usage_highlight' // Day 10-12 soft mention of usage stats
  | 'upgrade_prompt'  // Day 12-13 upgrade CTA with stats
  | 'expired';        // Day 14 downgrade notification

/**
 * Pending signup token status.
 */
export type SignupTokenStatus = 'pending' | 'used' | 'expired';

/**
 * Nudge delivery status.
 */
export type NudgeStatus = 'pending' | 'delivered' | 'dismissed' | 'acted_on';

// ===========================================================================
// Core Models — D1 Row Types
// ===========================================================================

/**
 * User — a registered person using the Network Manager.
 * Created after web signup (converts from PendingSignup).
 */
export interface UserRow {
  id: string;                    // UUID primary key
  phone: string;                 // E.164 format (+1XXXXXXXXXX), unique
  email: string | null;          // Set during web signup
  name: string;                  // Collected during onboarding
  pin_hash: string | null;       // bcrypt hash of 4-digit PIN
  passphrase: string | null;     // Backup passphrase (hashed)
  last_pin_verified: string | null; // ISO timestamp — trust window anchor
  account_locked: number;        // 0 = unlocked, 1 = locked (D1 has no boolean)
  failed_pin_attempts: number;   // Reset on success, lock at threshold
  subscription_tier: SubscriptionTier;
  trial_ends_at: string | null;  // ISO timestamp — null if never trialed
  stripe_customer_id: string | null;
  /**
   * Optional gender — set during onboarding or in settings.
   * When set, enables gender-aware nudge defaults via GenderModifiers
   * in intent-config.ts. null = not set (no modifiers applied).
   *
   * This is opt-in and functions as a suggestion layer, not a hard
   * rule. Users can override any cadence or nudge style preference
   * regardless of this setting.
   *
   * @see UserGender type
   * @see GENDER_MODIFIERS in shared/intent-config.ts
   */
  gender: UserGender;
  /** Onboarding stage — tracks where the user is in the SMS onboarding flow. null = complete. */
  onboarding_stage: OnboardingStage | null;
  /**
   * Last time we offered to help sort unsorted contacts.
   * Used to avoid spamming users with weekly sorting check-ins.
   * null = never offered.
   *
   * @see worker/services/sorting-checkin-service.ts
   */
  last_sorting_offer: string | null;
  /**
   * Last time we sent a trial lifecycle message.
   * Used to track timing of trial messaging.
   * null = no trial message sent yet.
   *
   * @see worker/services/trial-messaging-service.ts
   */
  last_trial_reminder: string | null;
  /**
   * Which trial reminder stage was last sent.
   * Ensures we don't re-send the same message.
   * null = no trial message sent yet.
   *
   * @see TrialReminderStage type
   * @see worker/services/trial-messaging-service.ts
   */
  trial_reminder_stage: TrialReminderStage | null;
  created_at: string;            // ISO timestamp
  updated_at: string;            // ISO timestamp
}

/**
 * Contact — a person in the user's network.
 * Circles are linked via the contact_circles junction table.
 */
export interface ContactRow {
  id: string;                    // UUID primary key
  user_id: string;               // FK → users.id
  name: string;
  phone: string | null;          // E.164 format, optional
  email: string | null;
  intent: IntentType;
  custom_cadence_days: number | null; // Override intent default, null = use intent default
  last_contact_date: string | null;   // ISO timestamp
  health_status: HealthStatus;        // Computed, stored for query performance
  /**
   * Whether this contact is family (kin) or not.
   * Kin contacts get relaxed cadence thresholds via kinDecayModifier
   * in intent-config.ts. Defaults to 'non_kin'.
   *
   * Auto-set to 'kin' when a contact is added to the "Family" circle,
   * but can be manually overridden (some close friends are like family,
   * and some family members are estranged).
   */
  contact_kind: ContactKind;
  notes: string | null;               // Free-form notes about this person
  source: string | null;              // How they were added: 'onboarding', 'braindump', 'manual', 'import'
  archived: number;                   // 0 = active, 1 = archived (soft delete)
  created_at: string;
  updated_at: string;
}

/**
 * Circle — a named group for organizing contacts.
 * Each user gets default circles on signup; can create custom ones.
 */
export interface CircleRow {
  id: string;                    // UUID primary key
  user_id: string;               // FK → users.id
  name: string;
  type: CircleType;
  default_cadence_days: number | null; // Suggested cadence for contacts in this circle
  sort_order: number;            // Display ordering
  created_at: string;
  updated_at: string;
}

/**
 * ContactCircle — many-to-many junction between contacts and circles.
 */
export interface ContactCircleRow {
  contact_id: string;            // FK → contacts.id
  circle_id: string;             // FK → circles.id
  added_at: string;              // ISO timestamp
}

/**
 * Interaction — a logged touchpoint between user and contact.
 */
export interface InteractionRow {
  id: string;                    // UUID primary key
  user_id: string;               // FK → users.id (denormalized for query speed)
  contact_id: string;            // FK → contacts.id
  date: string;                  // ISO timestamp — when the interaction happened
  method: InteractionMethod;
  summary: string | null;        // Brief description or AI-generated summary
  logged_via: string;            // 'sms', 'dashboard', 'auto' — how it was recorded
  created_at: string;
}

/**
 * PendingSignup — temporary record created during SMS onboarding.
 * Converted to a real User on web signup completion.
 */
export interface PendingSignupRow {
  id: string;                    // UUID primary key
  token: string;                 // Unique signup token (URL-safe, 32 chars)
  phone: string;                 // E.164 format
  name: string | null;           // Collected during onboarding
  circles_discussed: string;     // JSON array of circle names from conversation
  onboarding_context: string | null; // JSON — any extra context from the conversation
  status: SignupTokenStatus;
  created_at: string;
  expires_at: string;            // 24 hours after creation
  used_at: string | null;
}

/**
 * UsageTracking — daily/weekly usage counters per user.
 * Enforces free tier limits and tracks engagement.
 */
export interface UsageTrackingRow {
  id: string;                    // UUID primary key
  user_id: string;               // FK → users.id
  date: string;                  // YYYY-MM-DD — the day this row covers
  messages_sent: number;         // SMS messages processed today
  nudges_generated: number;      // Nudges created today
  contacts_added: number;        // Contacts added today
  braindumps_processed: number;  // Braindump parses today
  created_at: string;
}

/**
 * Nudge — a Bethany-generated reminder to reach out to someone.
 * Generated by cron, delivered via SMS during the morning window.
 */
export interface NudgeRow {
  id: string;                    // UUID primary key
  user_id: string;               // FK → users.id
  contact_id: string;            // FK → contacts.id
  message: string;               // Bethany's nudge text
  reason: string;                // Why this nudge was generated (health status, cadence, etc.)
  status: NudgeStatus;
  scheduled_for: string;         // ISO timestamp — when to deliver
  delivered_at: string | null;
  dismissed_at: string | null;
  acted_on_at: string | null;
  created_at: string;
}

// ===========================================================================
// Application-Level Types (camelCase, enriched)
// ===========================================================================

/**
 * Contact with circles resolved — used by API responses and dashboard.
 */
export interface ContactWithCircles extends ContactRow {
  circles: CircleRow[];
}

/**
 * Contact summary — lightweight version for list views.
 */
export interface ContactSummary {
  id: string;
  name: string;
  intent: IntentType;
  health_status: HealthStatus;
  contact_kind: ContactKind;
  last_contact_date: string | null;
  circles: Array<{ id: string; name: string }>;
}

/**
 * User with subscription state resolved.
 */
export interface UserWithSubscription extends UserRow {
  is_trial_active: boolean;
  is_premium: boolean;
  days_until_trial_expires: number | null;
}

/**
 * Onboarding conversation state — stored in Durable Object.
 * Not persisted in D1; lives only during the onboarding flow.
 *
 * Updated for web-first flow (TASK-36776bae-4). Now includes userId
 * (known from web signup), email, and richer people tracking.
 *
 * @see worker/services/onboarding-service.ts for OnboardingConversationState
 *      which extends this with additional fields for the DO.
 */
export interface OnboardingState {
  phone: string;
  userId: string;                // Known from web signup
  stage: OnboardingStage;
  name: string;                  // Known from web signup (not null anymore)
  circlesDiscussed: string[];
  peopleDiscussed: Array<{
    name: string;
    relationship?: string;
    circle?: string;
    notes?: string;
  }>;
  messages: Array<{
    role: 'user' | 'bethany';
    content: string;
    timestamp: string;
  }>;
  startedAt: string;
  lastMessageAt: string;
}

/**
 * Braindump extraction result — returned by the AI parser.
 */
export interface BraindumpExtraction {
  contacts: Array<{
    name: string;
    phone?: string;
    email?: string;
    suggested_intent?: IntentType;
    suggested_circles?: string[];
    notes?: string;
    confidence: 'high' | 'medium' | 'low';
  }>;
  interactions: Array<{
    contact_name: string;
    date?: string;
    method?: InteractionMethod;
    summary: string;
    confidence: 'high' | 'medium' | 'low';
  }>;
  unresolved: string[]; // Text fragments the AI couldn't parse
}

// ===========================================================================
// Service Method Params
// ===========================================================================

/**
 * Filters for listing contacts.
 */
export interface ContactListFilters {
  circle_id?: string;
  intent?: IntentType;
  health_status?: HealthStatus;
  contact_kind?: ContactKind;
  archived?: boolean;
  search?: string;           // Name search (LIKE query)
}

/**
 * Input for creating a new contact.
 */
export interface CreateContactInput {
  name: string;
  phone?: string;
  email?: string;
  intent?: IntentType;       // Defaults to 'new'
  custom_cadence_days?: number;
  contact_kind?: ContactKind; // Defaults to 'non_kin'
  notes?: string;
  circle_ids?: string[];     // Circles to link on creation
  source?: string;
}

/**
 * Input for updating an existing contact.
 */
export interface UpdateContactInput {
  name?: string;
  phone?: string;
  email?: string;
  intent?: IntentType;
  custom_cadence_days?: number | null;
  contact_kind?: ContactKind;
  notes?: string;
  archived?: boolean;
  circle_ids?: string[];     // Replaces all circle links if provided
}

/**
 * Input for logging an interaction.
 */
export interface LogInteractionInput {
  contact_id: string;
  date?: string;             // Defaults to now
  method: InteractionMethod;
  summary?: string;
  logged_via?: string;       // Defaults to 'dashboard'
}

/**
 * Free tier limits — centralized so they can be tuned.
 */
export const FREE_TIER_LIMITS = {
  max_contacts: 15,
  max_messages_per_day: 10,
  max_braindumps_per_day: 1,
  max_nudges_per_day: 3,
  max_sorting_per_week: 5,
} as const;

/**
 * Default circles created for new users.
 */
export const DEFAULT_CIRCLES = [
  { name: 'Family', type: 'default' as CircleType, sort_order: 1 },
  { name: 'Friends', type: 'default' as CircleType, sort_order: 2 },
  { name: 'Work', type: 'default' as CircleType, sort_order: 3 },
  { name: 'Community', type: 'default' as CircleType, sort_order: 4 },
] as const;
